version: '3'

services:
  app:
    container_name: app
    image: 'docker-spring-boot-test:latest'
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=baitap2_hangkhong;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_USERNAME=sa
      - SA_PASSWORD=sa123